### ISSUE TITLE
Clarify problem statement of Inverted Pendulum

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#1]
@smiths Please review my problem statement which is related to Inverted Pendulum.

**Comment by smiths** [comment]
@MinMah23 your problem statement is a great start, but I would like you to do some edits to clarify the statement, as follows:
- add some references, in particular, I would like links to the existing inverted pendulum calculators that are on-line.  Those will be valuable resources to you.
- clarify the inputs and outputs.  Your inputs and outputs imply that the input is one angle and the output is one force.  The solution will involve solving an ODE, so the output at least should be a function.  You might chose to characterize the output as a time series.  The input should also include how you are going to perturb the pendulum.  Is your inverted pendulum stabilized by applying a force at the base, or by displaying the base, for instance using a cart?
- For the environment, I don't see any reason to have a constraint that it only works on Windows 10.  Your software will be fairly simple, so I think it should run on any OS.  This also helps me, since I'd rather test it on my Mac than have to find a Windows machine, or install a virtual one.  :smile:

@MinMah23, in the future, please assign me review issues of this nature using the Assignees option for each issue in GitHub.  Please also include a hyperlink to the document you wish to have reviewed.

@MinMah23, you haven't yet done a merge request for `Repos.csv`.  Please do so.

I'll approve your project once you have made the above changes.

I'll change the assignment of the issue to you now.  You can assign it back to me, or create a new issue, when the changes are ready for review.

**Comment by MinMah23** [comment]
Dear @smiths,
Hope you have a great snowy day.

My project is inverted pendulum, more specifically one single pole mounted on a cart that is only able to move in one direction. The goal is to keep the pole upright and stabilized by using a control system. As I searched and read, there are two approaches: first by applying a torque at the pivot point and second by oscillating the pivot point vertically (Kapitza's pendulum, as the online calculator which you sent me). I am interested in the first method and their equations of motion. 
I couldn't find any online calculator for pendulum on the cart, there are lots of videos and websites, but I didn't see the appropriate reference.

On the other hand, the inputs of the control system will be are the angular position of the pendulum, and the horizontal position of the cart and the external force to the cart which moves it would be the output. Although there are lots of parameters such as mass of the card, mass of the pendulum, pendulum length and so on. Should I mention all variables? Am I getting the system’s input and output right?

I appreciate your help.

**Comment by smiths** [comment]
@MinMah23 thank you for the clarification.  I will approve your project.  We can work out the details on the inputs and outputs through your SRS.  From what you are describing, I believe your input is the original configuration of the pendulum, including the geometry, material properties and initial perturbation.  The outputs will be the torque as a function of time to restore equilibrium and the position of the pendulum as a function of time.

**Comment by smiths** [comment]
Since the project has been approved, I will close this issue.
