### ISSUE TITLE
VnV Plan review: Non-functional requirement

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#27]
- [x] In Section 5.2.1 -> test 1 -> Requirement IDs() is continue after the initial state. 
- [x] Input/condition is also continue to the requirement IDs. 
- [x] In Section 5.2.2 --> Test 1 -> In condition, it's good to describe condition but "checklist" and "domain expert" information are redundant there. 
- [x] In Section 5.2.2 --> Test 1 -> output, feedback is a single word. Don't add space. 
- [x] In Section 5.2.2 --> Test 1 -> How test should perform, can add more information about domain expert and checklist. 
- [x] In Section 5.2.2 --> Test 1 -> First line -> "usability Testing the usability..." I think newline should be added. 
- [x] In Section 5.2.3 --> Test 1 -> First line -> "accuracy The accuracy ...." I think newline should be added. 
- [ ] In Section 5.2.3 --> Test 1 -> Last line of intro -> by the other engineer and using Matlab" ?? I am not sure about what you are trying to say. I think you should take a look into it.

**Comment by MinMah23** [comment]
All the comments have been corrected except the last one and committed be2e110 in . I will close this issue and make another because I have this problem with testing Accuracy, I do not have any experimental data, I want to check my result with  program which written in another language by somebody else.
