### ISSUE TITLE
Continue of issue #29

### ISSUE THREAD

**Issue by MinMah23** [MinMah23/CAS741-Project#30]
Continue of issue #29:

I have updated my VnV based on the feedback in commit a0e4982, however, There are some parts I really need your help:

- In  my input tests, I have a test that the external force is zero, the comment is "This is confusing to have with tests for input validation. I’m also not sure you are right, since you will be violating the small angle assumption."

I don't have that assumption, because I think, I have no limitation about the angle to be small and if I don't apply any force to the cart, the pendulum will fall and it will be what it's expected.

- I got the idea of defining the external force (f) as a function of time but I couldn't find any useful solution, is there any other solution?

- In my output validation in table 3, I put some errors as expected output when the inputs are not as thy should be, and the comment is that " these sounds the input checking tests", but they are my expected error output when the user get me unexpected output, Did I get that wrong?

- About the accuracy testing and the results of comparing of the outputs of my tool and the pseudo-oracle will be described, you have mentioned to express how accuracy is affected by time-step size. I want to make sure that I got it write, so I should calculate the relative error of both tools and then plot it over time? 

Thank you so much for your continuous help to improving us.

**Comment by smiths** [comment]
@MinMah23 I haven't looked at the derivation of your equations, but in the case of a regular pendulum (on inverted) the derivation uses the fact that sin(x) is approximately equal to x for small angles.  I believe the inverted pendulum makes the same assumption.

For a balanced F(t) it is going to likely be some kind of sinusoidal solution.  You could try a(sin(bt)), or something similar.

If you have access to a program that solves the full control problem (not just the simulation part), you can take your F(t) as the output from that program.  That would be a really neat test case.  :smile:

With respect to distinguishing output and exceptions, it is best to think of them separately.  If your test will raise an exception because of invalid input, then you don't care what the output is, but you do care that an exception is raised.

My comment about the influence of the time step on accuracy is to remind you that your VnV plan can include plans for "numerical experiments" to describe the software, rather than specify the software.  You run your software with various inputs and observe how changes in those inputs change the solution.  Changing the time step will change the accuracy of your solution.  You could potentially have a plot showing time step as the independent variable and error as the dependent variable.  This experiment depends on you having a pseudo-oracle that will let you measure accuracy.
