### ISSUE TITLE
Comments for MIS

### ISSUE THREAD

**Issue by DeeshaPatel** [MinMah23/CAS741-Project#36]
- [ ] It will be a good idea if you add parameter name in input and output in "Exported Access Program". 
- [ ] What is "m_pmin, m_pmax, l_p and i_p" in Input Module? [Try to add it in Section 2] 
- [x] Do you think "The" is required in 6.4.3 for different lines in inputs. 
- [ ] You should add input subsection in load_input(), also write none for output for clear tracking of inputs and outputs of the function (Section 6.4.4)
- [ ] As per your description, the verify_input() is called by load_inputs() function. So, verify_input() can not be an exported program. 
- [ ] You can move your verify_input() to the local function. 
- [x] Add space after :=m_c in InputM.M_c
- [x] remove / before InputM.f_external 
- [ ] For your output parameter module, I think file is an output. So, exported program should have that information. 
- [ ] verify_output() is local method which is internally called by the output(). So, remove it from exported program and add it in local function. 
- [ ] As per your MG, Constant Module is related to conditions. But your MIS don't contain anything related to conditions. 
- [ ] Your load_input internally called verify_input and your verify_output called by output(). So, you don't need to call it again in your Control Module -> transition. 
- [x] what is y_inicond? 
- [x] Page number 13: "We have two coupled ODE in the IP which s is theta the first one and x in the second one" - Ambiguous statement. 
- [x] Missing information about local function in Plotting Module. 
- [x] Appendix table is out of the paper layout. 

---------------------------------------------------------------------------------------  

- [ ] If you are agree to change your design for "low coupling" between your Input/Output module and Constant Parameter Module, it would be a good for you as it will add high quality of the system. -- This is just my suggestion. :)"

**Comment by MinMah23** [comment]
Dear @DeeshaPatel,
I appreciate your time and useful comments, I corrected some of them in commit adf2161 and have question about the others as below:

1. About the first and second comments: I store all the constraints and conditions on parameters in Constraint Module, parameters like m_cmin  and so on, and check the inputs with that module when I want to verify the inputs, so do you think I should add the constants again in Input Module? About the Output module, which parameters you mean?
2. In your comment, "You should add input subsection in load_input(), also write none for output for clear tracking of inputs and outputs of the function (Section 6.4.4)", I checked the template, it does not have "input" subsection and I described the input in "transition" subsection. This module also has transition section, so it does not need output subsection, a module has one of them.
3. In the following comments: "As per your description, the verify_input() is called by load_inputs() function. So, verify_input() can not be an exported program., You can move your verify_input() to the local function., verify_output() is local method which is internally called by the output(). So, remove it from exported program and add it in local function., Your load_input internally called verify_input and your verify_output called by output(). So, you don't need to call it again in your Control Module -> transition.", all the comments related to the verify functions, I don't see verification segment as a part of load_input or output. They are different functions in a module, my Input Module has two function, first the load_inputs, load all the inputs from an input file and store them in data structure and the verify-input, read them and check them against the constants in Constant module. The same story for the output, Am I wrong?
4. In "As per your MG, Constant Module is related to conditions. But your MIS don't contain anything related to conditions." comment, what do you mean by condition, because I meant the constraints and conditions of valid inputs.


Thank you for your help, : *

**Comment by DeeshaPatel** [comment]
Related to comment 1: My suggestion is that you have used name of the parameters in some exported access program. For example, in your Output Parameter Module (M7) -> 7.3.2 -> in "In" column, you used parameter name "FOName". But if I see other module like f_external() and load_inputs in 6.3.2, there is no parameter name in "In" and "Out" section. You can either just remove the name of the parameters from every Exported Access Program or Keep it everywhere.

**Comment by DeeshaPatel** [comment]
For your second comment, That was my mistake. I am sorry. I realised it after sam's comment.

**Comment by DeeshaPatel** [comment]
For your 3rd comment, I will explain you in person for more clarity.

**Comment by DeeshaPatel** [comment]
4th comment is already solved as we talked.

**Comment by MinMah23** [comment]
I've updated in commit 4f6515a. Thank you
